import sqlite3
import json
from typing import List, Dict, Any, Set
from .models import Node, Edge

class NodeDAO:
    def __init__(self, conn: sqlite3.Connection):
        self.conn = conn

    def load_nodes_by_type(self, node_type: str) -> List[Node]:
        cursor = self.conn.cursor()
        cursor.execute("SELECT node_id, type, label, properties FROM nodes WHERE type = ?", (node_type,))
        nodes = []
        for row in cursor.fetchall():
            props = {}
            if row[3]:
                try:
                    props = json.loads(row[3])
                except Exception:
                    pass
            nodes.append(Node(id=row[0], type=row[1], label=row[2], properties=props))
        return nodes

    def load_all_nodes(self) -> List[Node]:
        cursor = self.conn.cursor()
        cursor.execute("SELECT node_id, type, label, properties FROM nodes")
        nodes = []
        for row in cursor.fetchall():
            node_type = row[1]
            if node_type == "tag":
                continue
            props = {}
            if row[3]:
                try:
                    props = json.loads(row[3])
                except Exception:
                    pass
            # Only include books and shelves generated by the graphify clustering
            if node_type in ("book", "shelf") and props.get("source") != "graphify_cluster":
                continue
            nodes.append(Node(id=row[0], type=node_type, label=row[2], properties=props))
        return nodes


    def write_node(self, node: Node):
        cursor = self.conn.cursor()
        cursor.execute(
            "INSERT OR REPLACE INTO nodes (node_id, type, label, properties) VALUES (?, ?, ?, ?)",
            (node.id, node.type, node.label, json.dumps(node.properties))
        )

    def delete_graphify_nodes(self):
        cursor = self.conn.cursor()
        cursor.execute(
            "DELETE FROM nodes WHERE type IN ('book', 'shelf') AND properties LIKE '%\"source\": \"graphify_cluster\"%'"
        )

class EdgeDAO:
    def __init__(self, conn: sqlite3.Connection):
        self.conn = conn

    def load_page_tags_batch(self, page_ids: List[str]) -> Dict[str, List[str]]:
        if not page_ids:
            return {}
        cursor = self.conn.cursor()
        placeholders = ",".join("?" for _ in page_ids)
        query = f"SELECT source_node_id, target_node_id FROM edges WHERE relation_type = 'tag' AND source_node_id IN ({placeholders})"
        cursor.execute(query, page_ids)
        
        result = {pid: [] for pid in page_ids}
        for source, target in cursor.fetchall():
            tag = target.replace("__tag__:", "")
            if source in result:
                result[source].append(tag)
        return result

    def write_edge(self, edge: Edge):
        cursor = self.conn.cursor()
        cursor.execute(
            "INSERT OR REPLACE INTO edges (edge_id, source_node_id, target_node_id, relation_type, weight) VALUES (?, ?, ?, ?, ?)",
            (edge.id, edge.source, edge.target, edge.relation, edge.weight)
        )

    def delete_graphify_edges(self):
        cursor = self.conn.cursor()
        cursor.execute(
            "DELETE FROM edges WHERE edge_id LIKE 'book-%' OR edge_id LIKE '%-sits_on-shelf-%'"
        )

    def load_all_edges(self) -> List[Edge]:
        cursor = self.conn.cursor()
        cursor.execute("SELECT edge_id, source_node_id, target_node_id, relation_type, weight FROM edges")
        edges = []
        for row in cursor.fetchall():
            edges.append(Edge(id=row[0], source=row[1], target=row[2], relation=row[3], weight=row[4]))
        return edges
